Mise en place, refactorisation du système Leaflet
epsi-mspr-antd/frontend pull request #23
Opened 2024-05-31 17:31 UTC by JesseeDantonio

2024-05-31 18:29 UTC, TristanEPSI approved these changes

2024-06-02 11:03 UTC, TristanEPSI approved these changes

2024-06-02 12:42 UTC, Mageas requested changes
Il y a des changements à faire:
- Changer le GET en un service que Tristan a fait.
- Faire un seul point pour les plantes avec la même adresse.

2024-06-02 12:46 UTC, TristanEPSI commented on src/Components/Map/map.component.tsx
> +    const fetchData = async () => {
Essaie de faire passer le fetch dans un service. Normalement tu pourras retrouver des exemples si tu es à jour dans /utils/API. Pour l'access Token, tu as aussi pour chaque méthode API des exemples de comment l'intégrer; On doit aller le chercher dans le localStorage à chaque fois.

2024-06-02 12:48 UTC, TristanEPSI commented on src/Components/Map/map.component.tsx
> +                            console.log(item);
Attention au console.log si c'est un oubli (j'ai du en oublier aussi d'ailleurs ! )

2024-06-02 12:49 UTC, TristanEPSI commented on src/Interface/Leaflet/IPlantProperties.tsx
Normalement, tu devrais avoir une Interface qui type déjà la plante, à vérifier.

2024-06-08 07:19 UTC, closed without merging