Jessee
epsi-mspr-antd/frontend pull request #28
Opened 2024-06-08 07:19 UTC by JesseeDantonio

2024-06-17 11:21 UTC, TristanEPSI commented on src/Components/Account/AccountAddPlant/AddPlant.style.css
Avec cette écriture, on applique les règles css qui suivent à tous les input et select. Il faut être sûr que cela soit notre souhait.

2024-06-17 11:23 UTC, TristanEPSI commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +      console.log(plantGuardedIds.filter(plantId => plantId !== id));
Volontaire de laisser le console.log ? (Pas vraiment un problème)

2024-06-17 11:26 UTC, TristanEPSI approved these changes

2024-06-18 08:26 UTC, Mageas requested changes

2024-06-18 08:26 UTC, Mageas commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +  const [plantGuardedIds, setPlantGuardedIds] = useState<number[]>(plantGuard);
Il y a un probleme, la logique ne marche pas. Pour etre plus precis elle marche seulement au chargement de la page.

2024-06-18 08:26 UTC, Mageas commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +            plantIds.forEach(id => {
Refaire la logique, j'ai une seul plante qui est guard et non toutes les plantes

2024-06-18 08:26 UTC, Mageas commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +  const plantIds = ids ? ids.split(',') : [];
Refaire cette logique pour etre compatible avec React.

2024-06-18 08:32 UTC, Mageas requested changes

2024-06-18 08:32 UTC, Mageas commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +  const { guardians, loadingGuardian } = useUsersGuardingPlant("1");
Pourquoi 1 ? Il faut changer par l'id

2024-06-19 13:27 UTC, JesseeDantonio commented on src/Components/Map/SpecificAddress/SpecificAddressList.component.tsx
> +  const { guardians, loadingGuardian } = useUsersGuardingPlant("1");
C'est réglé ;)

2024-07-10 11:57 UTC, closed without merging